### PR TITLE
Add quiet option to hide php process output

### PR DESCRIPTION
**Pull request by webdevian**

### CODE REVIEW

**Comment by oscarotero** [comment]
What do you think about changing the `quiet` option for a more generic `stdio`?

**Comment by webdevian** [comment]
Yeah that would work, and default it to inherit?

**Comment by oscarotero** [comment]
Yes, exactly.
Would you mind to commit this change? I'd be happy to merge it.

**Comment by oscarotero** [comment]
Perfect. Thank you!

**Pull request merged**
